log:
  level: INFO  # DEBUG INFO WARNING ERROR
  file: "xerxes_node.log"
  
database:
  name: "test"
  collection: PRJ-16

uploader:
  upload_period: 10  # how often to push to DB, [s]

system:
  work_dir: "/tmp/xerxes"  # where to store measurements
  log_dir: "/var/log/xerxes"  # where to store logs

  workers:
    - label: "worker1"
      period: 1 # seconds
      leaves: 
        - address: 0
          label: "XAL-1"
          root: "usb0"
          values:
            x:  pv0
            y:  pv1
            z:  pv2
            t:  pv3

    - label: "worker60"
      period: 5 # seconds
      leaves: 
        - address: 0
          label: "XAL-1"
          root: "usb0"
          values:
            fft: fft
  
  roots: 
    - label: "usb0"
      device: "/dev/ttyUSB0"
      baudrate: 115200
      timeout: 0.02
  


# to test, create a virtual serial port with socat: 
# socat -d -d pty,raw,echo=0 pty,raw,echo=0