#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
from pprint import pprint as print 
import socket

print(f"Hostname: {socket.gethostname()}")
print(f"SPI devices: {os.popen('ls /dev|grep spi').read()}")