#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import logging
from pymongo import MongoClient, UpdateOne
from pymongo.collection import Collection
from threading import Thread
import os
import time
import json

log = logging.getLogger(__name__)

"""This module looks for new entries generated by worker and uploads them to the
database."""


class Uploader:
    worker: Thread

    def __init__(
        self, collection: Collection, workdir: str, upload_period: int = 10
    ):
        self.col = collection

        # check if measurements directory exists, if not create it
        if not os.path.isdir(workdir):
            try:
                os.mkdir(workdir)
            except:
                raise AttributeError(f"Directory {workdir} does not exist.")

        self._directory = workdir
        self._upload_period = upload_period

    def start(self) -> Thread:
        """Start new thread which periodically checks for new entries and
        uploads them to the database.

        returns: Thread object of the thread.
        """

        self._run = True
        self.worker = Thread(target=self._upload)
        self.worker.start()
        return self.worker

    def stop(self) -> None:
        """Stop the thread."""
        self._run = False

        log.info("Waiting for uploader thread to finish...")
        # wait for thread to finish
        self.worker.join()

    @property
    def alive(self) -> bool:
        return self.worker.is_alive()

    def _upload(self) -> None:
        """Upload new entries to the database."""

        while self._run:
            operations = []

            for entry in os.listdir(self._directory):
                if entry.endswith(".dat"):
                    # unpickle data
                    filename = os.path.join(self._directory, entry)
                    with open(filename, "r") as f:
                        try:
                            data = json.load(f)
                        except EOFError:
                            log.warning(
                                f"Uploader encountered empty file {filename}"
                            )
                            continue

                    try:
                        keys = list(
                            data.keys()
                        )  # eg. XAL-1, XAL-2, XAL-3, time
                        # remove time from keys:
                        keys.remove("time")
                        to_set = {
                            f"{key}.{k}": data[key][k]
                            for key in keys
                            for k in data[key]
                        }
                        op = UpdateOne(
                            {"time.datetime": data["time"]["datetime"]},
                            {"$set": to_set},
                            upsert=True,
                        )
                        operations.append(op)

                        os.remove(filename)
                        log.info(f"New update added to queue")
                        log.debug(f"Operation: {op}")

                    except Exception as e:
                        # probably a timeout, try again in 10s
                        log.warning(
                            f"Unable to upload {entry} to database: {e}"
                        )
                        time.sleep(10)
            if operations:
                result = self.col.bulk_write(operations, ordered=False)
                log.info(f"Result of bulk operation: {result}")

            time.sleep(self._upload_period)

        log.warning("Uploader thread stopped.")
