name: xerxes-node # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: sensor node package # 79 char long summary
description: |
  TODO: REWRITE! this bullshit
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: [arm64, armhf, amd64]

# TODO: aby som mohol strict confinement musim toto uvolnit
#plugs:
#  system-files:
#    read:
#      - /etc/resolv.conf
#    write:
#      - /etc/resolv.conf

apps: 
  daemon:
    command: bin/worker
    # nasledujuce odkomentuj a bude spawnuty ako daemon
    daemon: simple
    restart-delay: 10s
    
    # allow access to SPI, I2C, I/O...
    plugs: [home, spi, io-ports-control, gpio] #, gpio-control, system-files, i2c]

  probe:
    command: bin/probe
  

parts:
  xerxes:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    # requirements: ["requirements.txt"]
    python-packages: [
      "pymongo==3.12.0",
      "dnspython==2.1.0",
      "spidev==3.5",
      "wiringpi==2.60.1",
      "PyYAML==5.3.1"
      ]