name: xerxes-node # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: sensor node package # 79 char long summary
description: |
  TODO: REWRITE! this bullshit
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: [arm64, armhf, amd64]

apps: 
  xerxes-node:
    command: bin/python3 main.py

parts:
  xerxes-node:
    # See 'snapcraft plugins'
    plugin: python
    source: ../
    # requirements: ../requirements.txt